### ISSUE TITLE
On [Uploading screen], display animated thumbnail (Android)

### ISSUE THREAD

**Issue by Bartalog** [Bartalog/cool-maze#420] opened 2019-08-26 10:56 UTC
Like #419, but on the Uploading view:

Display in bottom-left corner the thumbnail of the single picture being uploaded, in 2 parts:

- top X% solid
- bottom (100-X)% faded

Where X is the % of the file that is already uploaded.

Then, the [Success] view should keep the thumbnail displayed, still, 100% solid.

**Comment by Deleplace** [comment] 2022-12-28 23:12
Dupe of #252

**Closed by Deleplace** 2022-12-28 23:12 UTC
Labels: UX, Android
